image: docker:19.03.5
services:
  - docker:19.03.5-dind

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - deploy-staging
#  - deploy-prod
  - undeploy-staging
#  - undeploy-prod

#########################################
## Deploy common
#########################################
#
.common-deploy-script: &common-deploy-script |
  helm repo add bitnami https://charts.bitnami.com/bitnami
  helm install -f $CI_PROJECT_DIR/config/values.yaml ${ENV} bitnami/ghost
  sleep 10
  export APP_HOST=$(kubectl get ingress --namespace $KUBE_NAMESPACE | grep ghost | awk '{print $3}')
  export GHOST_PASSWORD=$(kubectl get secret --namespace $KUBE_NAMESPACE ${ENV}-ghost -o jsonpath="{.data.ghost-password}" | base64 -d)
  export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace $KUBE_NAMESPACE ${ENV}-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
  export MARIADB_PASSWORD=$(kubectl get secret --namespace $KUBE_NAMESPACE ${ENV}-mariadb -o jsonpath="{.data.mariadb-password}" | base64 -d)
  helm upgrade ${ENV} bitnami/ghost --set service.type=LoadBalancer,ghostHost=$APP_HOST,ghostPassword=$GHOST_PASSWORD,mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD,mariadb.auth.password=$MARIADB_PASSWORD
  kubectl rollout status deployment ${ENV}-ghost

########################################
# Deploy Ghost in staging
########################################
deploy-staging:
  stage: deploy-staging
  image: alpine/k8s:1.16.15
  when: manual
  variables:
    ENV: staging
  only:
    refs:
      - main
  script:
    - *common-deploy-script
  environment:
    name: staging-eks

########################################
# Deploy Ghost in prod
########################################
#deploy-prod:
#  stage: deploy-prod
#  image: alpine/k8s:1.16.15
#  when: manual
#  only:
#    refs:
#      - master
#  script:
#    - *common-deploy-script
#  environment:
#    ##TODO:: Update the name
#    name: prod-eks-KsVthwt8

########################################
# Un-deploy Ghost in staging
########################################
undeploy-staging:
  stage: undeploy-staging
  image: alpine/k8s:1.16.15
  when: manual
  variables:
    ENV: staging
  only:
    refs:
      - main
  script:
    - helm uninstall ${ENV}
  environment:
    name: staging-eks

########################################
# Un-deploy Ghost in prod
########################################
#undeploy-prod:
#  stage: undeploy-prod
#  image: alpine/k8s:1.16.15
#  when: manual
#  only:
#    refs:
#      - master
#  script:
#    - helm uninstall my-release
#  environment:
#    ##TODO:: Update the name
#    name: prod-eks-KsVthwt8
