image: docker:19.03.5
services:
  - docker:19.03.5-dind

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - deploy-staging
#  - deploy-prod
  - undeploy-staging
#  - undeploy-prod

#########################################
## Deploy common
#########################################
#
.common-deploy-script: &common-deploy-script |
  kubectl apply -f $CI_PROJECT_DIR/config/ingress-${ENV}.yaml
  helm repo add bitnami https://charts.bitnami.com/bitnami
  helm install -f $CI_PROJECT_DIR/config/values.yaml ${ENV} bitnami/ghost
  kubectl rollout status deployment ${ENV}-ghost

########################################
# Deploy Ghost in staging
########################################
deploy-staging:
  stage: deploy-staging
  image: alpine/k8s:1.16.15
  when: manual
  variables:
    ENV: staging
  only:
    refs:
      - main
  script:
    - *common-deploy-script
  environment:
    name: staging-eks

########################################
# Deploy Ghost in prod
########################################
#deploy-prod:
#  stage: deploy-prod
#  image: alpine/k8s:1.16.15
#  when: manual
#  only:
#    refs:
#      - master
#  script:
#    - *common-deploy-script
#  environment:
#    ##TODO:: Update the name
#    name: prod-eks-KsVthwt8

########################################
# Un-deploy Ghost in staging
########################################
undeploy-staging:
  stage: undeploy-staging
  image: alpine/k8s:1.16.15
  when: manual
  variables:
    ENV: staging
  only:
    refs:
      - main
  script:
    - helm uninstall ${ENV}
  environment:
    name: staging-eks

########################################
# Un-deploy Ghost in prod
########################################
#undeploy-prod:
#  stage: undeploy-prod
#  image: alpine/k8s:1.16.15
#  when: manual
#  only:
#    refs:
#      - master
#  script:
#    - helm uninstall my-release
#  environment:
#    ##TODO:: Update the name
#    name: prod-eks-KsVthwt8
